name: Playwright Tests
on:
  pull_request:
    branches:
      - main
  merge_group:
    branches:
      - main
jobs:
  test:
    timeout-minutes: 60
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - uses: actions/setup-node@v4
      with:
        node-version: 'lts/*'

    - name: Install dependencies
      run: npm install -g yarn && yarn

    - name: Install dependencies on auth sample
      run: yarn

    - name: Install Playwright Browsers
      run: yarn playwright install --with-deps
      working-directory: examples/apps/auth-sample

    - name: Run Playwright tests
      run: yarn playwright test
      working-directory: examples/apps/auth-sample

    - uses: actions/upload-artifact@v4
      if: ${{ !cancelled() }}
      with:
        name: playwright-report
        path: sdk/playwright-report/
        retention-days: 30
